# Generated by Django 5.0.6 on 2024-06-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsula',
            fields=[
                ('id_capsula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_capsula', models.CharField(max_length=50)),
                ('descripcion_capsula', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'capsula',
                'verbose_name_plural': 'capsulas',
            },
        ),
    ]
