# Generated by Django 4.2.13 on 2024-06-14 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes_Retiro',
            fields=[
                ('id_solicitudRetiro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_retiro', models.CharField(max_length=30)),
                ('fecha_realizarR', models.DateField()),
                ('descripcionRetiro', models.CharField(max_length=300)),
                ('cantidadRetiro', models.IntegerField()),
                ('estadoRetiro', models.BooleanField(default=False)),
                ('tipo_materialRetiro', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_usuario', models.CharField(choices=[('Trabajador', 'Trabajador'), ('Jefe', 'Jefe'), ('Administrador', 'Administrador')], max_length=30)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud_retiro',
                'verbose_name_plural': 'solicitudes_retiro',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes_Material',
            fields=[
                ('id_solicitudMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=30)),
                ('tipo_material', models.CharField(max_length=300)),
                ('fecha_realizarM', models.DateField()),
                ('descripcionMaterial', models.CharField(max_length=300)),
                ('cantidadMaterial', models.FloatField()),
                ('estadoMaterial', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_usuario', models.CharField(choices=[('Trabajador', 'Trabajador'), ('Jefe', 'Jefe'), ('Administrador', 'Administrador')], max_length=30)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud_material',
                'verbose_name_plural': 'solicitudes_material',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes_Epps',
            fields=[
                ('id_solicitudEpps', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEpps', models.CharField(max_length=30)),
                ('fecha_realizarEP', models.DateField()),
                ('descripcionEpps', models.CharField(max_length=300)),
                ('estadoEpps', models.BooleanField(default=False)),
                ('tipo_materialEpps', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_usuario', models.CharField(choices=[('Trabajador', 'Trabajador'), ('Jefe', 'Jefe'), ('Administrador', 'Administrador')], max_length=30)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud_epps',
                'verbose_name_plural': 'solicitudes_epps',
            },
        ),
    ]
